### PR TITLE
v0.25.0

### PR DESCRIPTION
**Pull request by chukarsten**
# v0.25.0 Jun. 1, 2021
### Enhancements
- Upgraded minimum woodwork to version 0.3.1. Previous versions will not be supported #2181
- Added a new callback parameter for ``explain_predictions_best_worst`` #2308
### Changes
- Deleted the ``return_pandas`` flag from our demo data loaders #2181
### Testing Changes
- Ignoring ``test_saving_png_file`` while building conda package #2323
### Breaking Changes
- Deleted the ``return_pandas`` flag from our demo data loaders #2181
- Upgraded minimum woodwork to version 0.3.1. Previous versions will not be supported #2181
- Due to the weak-ref in woodwork, set the result of ``infer_feature_types`` to a variable before accessing woodwork #2181

### CODE REVIEW

**Comment by freddyaboulton** [comment]
@chukarsten I think the PR description is showing the release notes for 0.24.2?

**Comment by chukarsten** [comment]
> @chukarsten I think the PR description is showing the release notes for 0.24.2?

Thanks for the quick QC @freddyaboulton !  It sure does because I didn't push my commit with the release notes adjusted, I think.

**Review by freddyaboulton — APPROVED** [review]
Performance tests look good to me @chukarsten !!

**Comment by angela97lin** [comment]
Cool beans--is the performance increase likely due to the WW upgrade? @freddyaboulton

**Comment by freddyaboulton** [comment]
@angela97lin I believe so! I saw a similar improvement when I was perf testing my feature branch.

**Pull request merged**
