### PR TITLE
Delete `drop_nan_target_rows` util method

### LINKED ISSUE #2684: Delete `drop_nan_target_rows` util method
There is a preprocessing util called `drop_nan_target_rows` but it isn't used anywhere. I'm not sure how useful this is, but it sounds like it should be replaced by data check action work. This issue tracks removing `drop_nan_target_rows`!

### PR DESCRIPTION
**Pull request by angela97lin**
Closes #2684

### CODE REVIEW

**Comment by jeremyliweishih** [comment]
instead of just deleting it, is there any value in changing it into a component?

**Comment by angela97lin** [comment]
> instead of just deleting it, is there any value in changing it into a component?

Good question, we have https://github.com/alteryx/evalml/issues/2705 to track that :) (Not explicitly dropping just NaN targets, but also rows in the features too)

**Comment by jeremyliweishih** [comment]
@angela97lin sounds good! it might be good to link this PR to that issue if we ever want to repurpose some of the code.

**Review by jeremyliweishih — APPROVED** [review]
👏

**Review by chukarsten — APPROVED** [review]
Love it and love stories like this.

**Pull request merged**
