### PR TITLE
Add DecisionTreeClassifier and DecisionTreeRegressor to AutoML

### LINKED ISSUE #1236: Add DecisionTreeClassifier and DecisionTreeRegressor to AutoML
Tracks adding DecisionTreeClassifier and DecisionTreeRegressor to EvalML and the appropriate perf testing

### PR DESCRIPTION
**Pull request by angela97lin**
Closes #1236 

Quip doc here: https://alteryx.quip.com/u5KjAUW92aeS/Adding-DecisionTree-Estimators-in-EvalML

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
@angela97lin I think this looks great! I left a comment on the performance tests explaining why I think it's ok to add these estimators to search.

**Review by jeremyliweishih — APPROVED** [review]
☘️

**Review by bchen1116 — APPROVED** [review]
Looks great!

**Review by dsherry — APPROVED** [review]
@angela97lin awesome!!! Love the analysis here.

I'd like to understand a bit more about what those 4 outlier datasets were in the validation accuracy graph. That said, I'd be shocked if those had anything to do with decision trees -- I suspect a bug with looking glass, or possibly a bug with automl. So, no need to hold merge for that. But let's discuss.

**Pull request merged**
