### PR TITLE
Run build_conda_pkg only on changes to requirements files

### LINKED ISSUE #2416: Speed up build_conda_pkg
Similar to #2365 and #2404 , `build_conda_pkg`is now a long pole in the CI tent.  Even though the rest of the CI jobs take ~10-12 minutes to run, this one is 30+ minutes and should either be moved to merges to main or effort put into shortening it.

### PR DESCRIPTION
**Pull request by freddyaboulton**
### Pull Request Description

Fixes #2416

We're "speeding up" the job by running it only when a dependency version is added/updated or when latest/min dependencies are updated.

-----
*After creating the pull request: in order to pass the **release_notes_updated** check you will need to update the "Future Release" section of* `docs/source/release_notes.rst` *to include this pull request by adding :pr:`123`.*

### CODE REVIEW

**Review by jeremyliweishih — APPROVED** [review]
nice! the build conda pkg check is hanging because it won't run but is required right? Will need an intervention to change that 😄

**Comment by freddyaboulton** [comment]
@jeremyliweishih Yes! I'm hoping @dsherry can help on Monday!

**Review by bchen1116 — APPROVED** [review]
Nice!

**Review by dsherry — APPROVED** [review]
@freddyaboulton ok, seems cool to me!

We may end up wanting to keep this enabled on merges to `main` just to have continuous proof things are alright. I am fine with removing it for now though.

**Comment by freddyaboulton** [comment]
@dsherry Modified the yaml so that it will run on merges to main!

**Pull request merged**
