### PR TITLE
Docs update for Mac graphviz

### PR DESCRIPTION
**Pull request by chukarsten**
Needed to update the Mac installation instructions to install graphviz so tests will pass.

### CODE REVIEW

**Review by dsherry — APPROVED** [review]
Looks good! 🚢

**Review by jeremyliweishih — APPROVED** [review]
nice! 🍾

**Review by freddyaboulton — APPROVED** [review]
Thanks @chukarsten !

**Review by bchen1116 — APPROVED** [review]
Nice! [This](https://evalml.alteryx.com/en/1655-update_docs_graphviz/install.html#Mac) is what it looks like

**Review by angela97lin — APPROVED** [review]
:shipit: 🚢

**Pull request merged**
