### PR TITLE
Set max_depth to 1 in dfs calls

### LINKED ISSUE #2219: Use max_depth=1 in code that uses featuretools to avoid warning
The latest featuretools release issues a warning when there is only one entity in the set and `max_depth` > 1. We should manually set `max_dept=1` in our components that use featuretools (DFSTransformer, TextFeaturizer) to avoid a warning. 

You can see this in the l[atest release changes CI](https://github.com/alteryx/evalml/runs/2480031411#step:9:234):

```
 Only one entity in entityset, changing max_depth to 1 since deeper features cannot be created
```

### PR DESCRIPTION
**Pull request by freddyaboulton**
### Pull Request Description
Fixes #2219

-----
*After creating the pull request: in order to pass the **release_notes_updated** check you will need to update the "Future Release" section of* `docs/source/release_notes.rst` *to include this pull request by adding :pr:`123`.*

### CODE REVIEW

**Review by angela97lin — APPROVED** [review]
Nice and clean, LGTM 👍

**Review by jeremyliweishih — APPROVED** [review]
nice catch!

**Review by bchen1116 — APPROVED** [review]
Nice!

**Review by dsherry — APPROVED** [review]
LGTM!

When we do the next release, let's make sure we run text datasets and see if this decreased the runtime.

**Pull request merged**
