### PR TITLE
Add partial dependence to API reference

### LINKED ISSUE #1516: Partial Dependence methods missing from api reference
I noticed a couple methods were missing from the model understanding section in the API Reference

* `partial_dependence`
* `graph_partial_dependence`

A side note, we might be able to better organize the model understanding section of the API Reference by group into some subsections

### PR DESCRIPTION
**Pull request by angela97lin**
Closes #1516 

Also does minor reorganization, separating out data utils from graphing utils, but open to other suggestions as to how to split up that section more 🤷 

image

### CODE REVIEW

**Review by jeremyliweishih — APPROVED** [review]
nice change!

**Review by freddyaboulton — APPROVED** [review]
Looks good! Should we make `_get_prediction_vs_actual_data` public? What do you think @bchen1116 ?

**Comment by bchen1116** [comment]
@angela97lin @freddyaboulton We can make `_get_predictions_vs_actual_data` public. It can be a useful function that allows users to get the data and do further analysis on it.

**Review by bchen1116 — APPROVED** [review]
Looks great! Thanks for cleaning this up

**Comment by angela97lin** [comment]
@freddyaboulton @bchen1116 Looks like unit tests are missing for `_get_predictions_vs_actual_data`, so filed an issue to track adding unit tests and making the API public: https://github.com/alteryx/evalml/issues/1542 😁

**Pull request merged**
