### PR TITLE
Rename "details" to "metadata" for data check actions

### LINKED ISSUE #1988: Rename "details" to "metadata" for data check actions
Following discussion w/ @dsherry and @chukarsten, it might be a better idea to rename "details" to "metadata"

### PR DESCRIPTION
**Pull request by angela97lin**
Closes #1988

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
Looks great to me! Is there a similar plan for the warning/error message classes?

**Comment by angela97lin** [comment]
@freddyaboulton Currently, no--I think this came up for actions because they're used as data/information elsewhere, whereas for "messages", details seems okay 😅  Open to discussion though, I could see it being a good idea for consistency, and also a good idea to keep as "details" to differentiate? :)

**Review by jeremyliweishih — APPROVED** [review]
Looks great! Nice refactor

**Review by bchen1116 — APPROVED** [review]
The attention to ~~detail~~ _metadata_

**Pull request merged**
