### PR TITLE
removed empty cell

### LINKED ISSUE #3206: Blank Cell in Documentaion
In reviewing docs for 0.41.0 release, found a blank cell that can be removed : https://evalml.alteryx.com/en/v0.41.0/demos/text_input.html.

image

### PR DESCRIPTION
**Pull request by Mahesh1822**
### Pull Request Description
I edited docs/source/demos/text_input.ipynb file 
and removed the empty cell mentioned in the issues

Fixes #3206 
-----
*After creating the pull request: in order to pass the **release_notes_updated** check you will need to update the "Future Release" section of* `docs/source/release_notes.rst` *to include this pull request by adding :pr:`123`.*

### CODE REVIEW

**Comment by jeremyliweishih** [comment]
Thanks @Mahesh1822! I'm going to approve the our tests to run but you would still need to do the following:

1. Sign the Contributor License Agreement 
2. Update the release notes by adding the "Future Release" section of `docs/source/release_notes.rst` to include this pull request by adding :pr:123.

**Comment by Mahesh1822** [comment]
> Thanks @Mahesh1822! I'm going to approve our tests to run but you would still need to do the following:
> 
> 1. Sign the Contributor License Agreement
> 2. Update the release notes by adding the "Future Release" section of `docs/source/release_notes.rst` to include this pull request by adding :pr:3233.

**Comment by Mahesh1822** [comment]
I'm new to this but I will try my best.

**Comment by Mahesh1822** [comment]
I did the changes now what to do ? I closed this PR I think

**Pull request closed without merging**
