### PR TITLE
Added label encoder to XGBoostClassifier

### LINKED ISSUE #2517: Add label encoder to XGBoostClassifier
I currently get the following DeprecationWarning with XGBoost==1.4.2:
```
  The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
```
Since I know we want to upgrade XGBoost to >1.4.2 for the pandas 1.3.0 release, it could be a good idea to address this too, sooner rather than later :)

### PR DESCRIPTION
**Pull request by kadatatlukishore**
### Pull Request Description

Fixes #2517

* Added label encoder to XGBClassifier.

### CODE REVIEW

**Comment by chukarsten** [comment]
@kadatatlukishore thanks for submitting this!  Could you add some unit tests to cover up the uncovered lines?  Also please run `make lint-fix` to lint it up.

**Comment by kadatatlukishore** [comment]
Thanks @chukarsten , Working on it.

**Comment by kadatatlukishore** [comment]
Hello @freddyaboulton , I've tried my best but still need help to resolve the failed test issues.

**Comment by freddyaboulton** [comment]
@kadatatlukishore Once again, thanks for working on this issue! 

The test is failing on the line

```
          assert xgb_classifier.describe(return_dict=True) == {
                "name": "XGBoost Classifier",
                "parameters": {
                    "eta": 0.1,
                    "max_depth": 3,
                    "min_child_weight": 1,
                    "n_estimators": 75,
                    "n_jobs": -1,
                },
            }
```

So in other words, it's expecting the parameters to be equal to the dictionary

```
"parameters": {
    "eta": 0.1,
    "max_depth": 3,
    "min_child_weight": 1,
    "n_estimators": 75,
    "n_jobs": -1,
},
```
but it looks like your pr adds `use_label_encoder: False` to the parameters dictionary. That means you need to change the test to expect `use_label_encoder: False` to be present in the parameters.

You can run the test locally with 

```
pytest evalml/tests/component_tests/test_components.py::test_describe_component
```

to see if your changes make the test pass!

**Comment by chukarsten** [comment]
Closing due to inactivity!

**Pull request closed without merging**
