### PR TITLE
v0.20.0

### PR DESCRIPTION
**Pull request by dsherry**
# v0.20.0 Mar. 10, 2021
### Enhancements
- Added a GitHub Action for Python windows unit tests #1844
- Added a GitHub Action for checking updated release notes #1849
- Added a GitHub Action for Python lint checks #1837
- Adjusted ``explain_prediction``, ``explain_predictions`` and ``explain_predictions_best_worst`` to handle timeseries problems. #1818
- Updated ``InvalidTargetDataCheck`` to check for mismatched indices in target and features #1816
- Updated ``Woodwork`` structures returned from components to support ``Woodwork`` logical type overrides set by the user #1784
- Updated estimators to keep track of input feature names during ``fit()`` #1794
- Updated ``visualize_decision_tree`` to include feature names in output #1813
- Added ``is_bounded_like_percentage`` property for objectives. If true, the ``calculate_percent_difference`` method will return the absolute difference rather than relative difference #1809
- Added full error traceback to AutoMLSearch logger file #1840
- Changed ``TargetEncoder`` to preserve custom indices in the data #1836
- Refactored ``explain_predictions`` and ``explain_predictions_best_worst`` to only compute features once for all rows that need to be explained #1843
- Added custom random undersampler data splitter for classification #1857
- Updated ``OutliersDataCheck`` implementation to calculate the probability of having no outliers #1855
- Added ``Engines`` pipeline processing API #1838
### Fixes
- Changed EngineBase random_state arg to random_seed and same for user guide docs #1889
### Changes
- Modified ``calculate_percent_difference`` so that division by 0 is now inf rather than nan #1809
- Removed ``text_columns`` parameter from ``LSA`` and ``TextFeaturizer`` components #1652
- Added ``random_seed`` as an argument to our automl/pipeline/component API. Using ``random_state`` will raise a warning #1798
- Added ``DataCheckError`` message in ``InvalidTargetDataCheck`` if input target is None and removed exception raised #1866
### Testing Changes
- Added back coverage for ``_get_feature_provenance`` in ``TextFeaturizer`` after ``text_columns`` was removed #1842
- Pin graphviz version for windows builds #1847
- Unpin graphviz version for windows builds #1851
### Breaking Changes
- Added a deprecation warning to ``explain_prediction``. It will be deleted in the next release. #1860

### CODE REVIEW

**Comment by dsherry** [comment]
Perf test results [here](https://alteryx.quip.com/tebGAWSQ48np/v0200-vs-v0190-perf-test-results).

To save time I reused last release's results for v0.19.0 but I forgot they were run with longer stopping criterion, whereas the v0.20.0 results used the default 😅  As a result the results are slightly wonky. But they demonstrate there was no significant performance regression, which is goal number 1.

**Review by angela97lin — APPROVED** [review]
🚢 !

**Review by jeremyliweishih — APPROVED** [review]
Nice!

**Review by freddyaboulton — APPROVED** [review]
The best pipeline score comparison looks good to me!

**Review by bchen1116 — APPROVED** [review]
🚀

**Pull request merged**
