### PR TITLE
Refactors for component_class loops to use pytest.mark.parametrize

### PR DESCRIPTION
**Pull request by harshvardhanb25**
### Pull Request Description
Fixes: #3621

I have fixed most of the for loops to use `@pytest.mark.parametrize` and have also updated the `if...continue` cases  to use `@pytest.mark.xfail`. One test case is currently failing but this was happening at the time of the initial fork.

-----
*After creating the pull request: in order to pass the **release_notes_updated** check you will need to update the "Future Release" section of* `docs/source/release_notes.rst` *to include this pull request by adding :pr:`123`.*

### CODE REVIEW

**Comment by jeremyliweishih** [comment]
hey @harshvardhanb25 - thanks for contributing! We need to manually approve your CI runs as you're a first time contributor but I just kicked them off. Please take a look at the failing CI and let me know if you have any questions on fixing them. Looks like you will need to update the release notes to pass the `Release notes updated` check. Once the CI is fix I'll give the PR a review!

**Comment by harshvardhanb25** [comment]
Hi @jeremyliweishih I have updated the release notes. I have updated the release notes. However, when I run pylint on componet_tests.py, I get several messages, most of which have nothing to do with the changes I have made to the code. Could you please guide me on how to fix this?

**Comment by jeremyliweishih** [comment]
@harshvardhanb25 in the EvalML repo you can run `make installdeps-dev` to install developer dependencies and then `pre-commit run` to make the lint fixes (if you try to commit after installing developer dependencies it should lint for you as well). Not sure what messages you're getting but we do not use pylint for linting since we use [black](https://github.com/psf/black). Let me know if this helps!

**Comment by harshvardhanb25** [comment]
@jeremyliweishih I think this should be it. I have updated the release notes and run the lint hooks. Thanks for your help!

**Comment by jeremyliweishih** [comment]
@harshvardhanb25 no worries! I will get to the review soon - thanks for helping out.

**Review by jeremyliweishih — CHANGES_REQUESTED** [review]
@harshvardhanb25 great work on this! Just two suggestions: 
1. could you remove the test level `@pytest.mark.xfail`? I think it is redundant with the `pytest.xfail()` calls within the test. 
2. instead of the using the if statements to call `pytest.xfail()` could we just use the `condition` [parameter](https://docs.pytest.org/en/7.1.x/how-to/skipping.html#condition-parameter) so that we retain information on why these cases were allowed to fail.

Point 1 is the important one but take a shot at point 2 (I can approve once point 1 is fixed 😄 )! Let me know how I can help.

**Comment by harshvardhanb25** [comment]
@jeremyliweishih I think `pytest.xfail()` does not take a condition parameter like `@pytest.mark.xfail` does. I tried doing this and the cases failed because of the additional parameter. Please let me know if there is something that might fix this. I am fixing the first issue you mentioned.

**Comment by jeremyliweishih** [comment]
@harshvardhanb25 I think you're correct! Thats my mistake 😄 will review once CI passes and will also get you another reviewer tmr. Thanks!

**Comment by harshvardhanb25** [comment]
@jeremyliweishih thanks for all your help😄. Looking forward to contributing more to this repo.

**Review by jeremyliweishih — APPROVED** [review]

**Comment by jeremyliweishih** [comment]
@harshvardhanb25 this PR LGTM, thanks for helping out!

**Review by chukarsten — APPROVED** [review]
Thanks!  If you want more commits for your Github portfolio, I plan on putting out some more of these refactoring type issues!

**Comment by harshvardhanb25** [comment]
@chukarsten that would be awesome! I’m really looking to get my hands on some problems I can try fixing.

**Pull request merged**
