### PR TITLE
Release v0.42.0

### PR DESCRIPTION
**Pull request by chukarsten**
# v0.42.0 Jan. 18, 2022
### Enhancements
- Required the separation of training and test data by ``gap`` + 1 units to be verified by ``time_index`` for time series problems #3208
- Added support for boolean features for ``ARIMARegressor`` #3187
- Updated dependency bot workflow to remove outdated description and add new configuration to delete branches automatically #3212
- Added ``n_obs`` and ``n_splits`` to ``TimeSeriesParametersDataCheck`` error details #3246
### Fixes
- Fixed classification pipelines to only accept target data with the appropriate number of classes #3185
- Added support for time series in ``DefaultAlgorithm`` #3177
- Standardized names of featurization components #3192
- Removed empty cell in text_input.ipynb #3234
- Removed potential prediction explanations failure when pipelines predicted a class with probability 1 #3221
- Dropped NaNs before partial dependence grid generation #3235
- Fixed bug where ``InvalidTargetDataCheck`` would not check time series regression targets #3251
### Changes
- Raised lowest compatible numpy version to 1.21.0 to address security concerns #3207
- Changed the default objective to ``MedianAE`` from ``R2`` for time series regression #3205
- Removed all-nan Unknown to Double logical conversion in ``infer_feature_types`` #3196
- Checking the validity of holdout data for time series problems can be performed by calling ``pipelines.utils.validate_holdout_datasets`` prior to calling ``predict`` #3208
### Breaking Changes
- Renamed ``DateTime Featurizer Component`` to ``DateTime Featurizer`` and ``Natural Language Featurization Component`` to ``Natural Language Featurizer`` #3192

### CODE REVIEW

**Comment by jeremyliweishih** [comment]
is the 3.7 test failure just a flake? @chukarsten

**Review by bchen1116 — APPROVED** [review]
LGTM! Seems like we have potential flakiness with one of the dask threaded tests, which would be nice to track down and fix if we can!

**Review by jeremyliweishih — APPROVED** [review]
much Gucciness!

**Comment by ParthivNaresh** [comment]
Looks great!

**Review by ParthivNaresh — APPROVED** [review]

**Comment by chukarsten** [comment]
I've added the information from this instance of flake to the discussion [here](https://github.com/alteryx/evalml/issues/2969).  It upsets me that we're seeing the "do you already have a cluster running?" type messages as I thought I fixed that with the modifications to the Engine.  But we'll have to backburner Head and Shoulderss'ing this for a bit.

**Review by freddyaboulton — DISMISSED** [review]
@chukarsten Looks good and perf tests look great! Blocking until we figure out some errors that this release is causing for our downstream users.

**Pull request merged**
