### PR TITLE
Revert "User Specified Date Feature"

### LINKED ISSUE #2215: Build Conda Package Failure during pmdarima installation
Regarding #2155 and by extension #2009 

We're currently [facing a failure](https://github.com/alteryx/evalml/runs/2478486827?check_suite_focus=true) of `build_conda_pkg` on `main` where `pmdarima` isn't being installed despite `has_minimal_dependencies` being set to False.

`AssertionError: The test environment is missing expected extra dependency 'pmdarima'. Please either install all requirements in requirements.txt, or rerun the tests with '--has-minimal-dependencies'.`

### PR DESCRIPTION
**Pull request by ParthivNaresh**
Fixes #2215 
Reverts alteryx/evalml#2155

Reverting until we can figure out what's going on with `pmdarima` during installation

### CODE REVIEW

**Review by dsherry — APPROVED** [review]
Thanks for keeping `main` green! Sorry you ran into trouble with conda. We can fix it 😁

**Comment by freddyaboulton** [comment]
@ParthivNaresh @dsherry  What happened?

**Comment by ParthivNaresh** [comment]
@freddyaboulton We moved ARIMA from the `statsmodel` implementation to `sktime` which has `pmdarima` as a soft dependency. So I guess this means we don't need `statsmodel?

**Comment by freddyaboulton** [comment]
Ah I read the diff wrong! The original date feature pr changed the underlying library used by Arima. 

Maybe what we should do then is add pmdarima to the conda recipe? Might need to remove `statsmodels` from our recipe though. I see pmdarima has a max statsmodels [version](https://github.com/conda-forge/pmdarima-feedstock/blob/master/recipe/meta.yaml#L34) that's lower than our min.

**Comment by freddyaboulton** [comment]
@ParthivNaresh Yea I don't think statsmodels is used by anything else. I think it's worth seeing if we can patch up the recipe before merging this pr?

**Comment by ParthivNaresh** [comment]
@freddyaboulton Sorry I didn’t see your message before merging (dang refreshing). But I’ll take a look at the recipe next for sure

**Pull request merged**
