### PR TITLE
Update Woodwork `to_pandas` to `to_dataframe` and `to_series`

### PR DESCRIPTION
**Pull request by angela97lin**
Update Woodwork `to_pandas` to `to_dataframe` and `to_series` after 0.5.0 release.

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
@angela97lin Looks good to me! Thanks for jumping on this so quickly. Do you know what's up with the coverage change with the ExtensionArray case in _conver_woodwork_types_wrapper?

**Review by bchen1116 — APPROVED** [review]
LGTM!

**Comment by angela97lin** [comment]
@freddyaboulton Just dug into this. Check this out:

WW 0.0.4:
Screen Shot 2020-11-12 at 11 28 16 AM

WW 0.0.5
Screen Shot 2020-11-12 at 11 29 05 AM

Looks like the return type has changed, hence why we no longer need the ExtensionArray. I'll remove it, see if anything breaks. If not, we can just delete those lines for now.

**Comment by freddyaboulton** [comment]
Good digging @angela97lin !

**Review by dsherry — APPROVED** [review]
Niiice! 🚢

**Pull request merged**
