### PR TITLE
Fix code in release notes

### PR DESCRIPTION
**Pull request by angela97lin**
Fixing all code blocks / inserts in our release notes to work properly (currently only italicized).

Updated docs here: https://evalml.alteryx.com/en/ange_fix_release_notes/release_notes.html

Note: In the future, we should use `` to indicate code blocks, rather than ` which is for italics.

### CODE REVIEW

**Review by bchen1116 — APPROVED** [review]
LGTM

**Review by jeremyliweishih — APPROVED** [review]
seems good!

**Review by freddyaboulton — APPROVED** [review]
Thank you for fixing this @angela97lin ! This looks great. The Stacked estimators don't look like code blocks right now in the docs you linked - I don't know if that's intended.

**Comment by angela97lin** [comment]
@freddyaboulton Ah I made that change pretty recently so the docs probably weren't updated / fully built. It's there now! 😁  (https://evalml.alteryx.com/en/ange_fix_release_notes/release_notes.html)

**Comment by dsherry** [comment]
Thank you @angela97lin ! Yep let's all try to remember to check the release notes for this before releasing and make sure they look good. I didn't do that. It is [listed in the pre-release checklist](https://github.com/alteryx/evalml/issues/144#issuecomment-701498916). I bet we could write CI for this someday too. 👍

**Pull request merged**
