### PR TITLE
Fix high variance cv message for automl

### LINKED ISSUE #1280: Fix logger message for HighVarianceCV Datacheck
We added a HighVarianceCV datacheck in #1254. This issue tracks checking if the logger output looks good!

@jeremyliweishih does this show up in the console in a well-formatted way? I've noticed that `str(check)` doesn't look great. You may have to call `.message`

_Originally posted by @dsherry in https://github.com/alteryx/evalml/pull/1254#discussion_r501840183_

### PR DESCRIPTION
**Pull request by angela97lin**
Closes #1280 
Fixes the high variance CV message during AutoML after the data checks API update:
image

Currently on main:

image

### CODE REVIEW

**Review by dsherry — APPROVED** [review]
Awesome!! 🚢

**Review by freddyaboulton — APPROVED** [review]
Thanks @angela97lin !!

**Comment by dsherry** [comment]
@angela97lin does this fix #1280?

**Comment by angela97lin** [comment]
@dsherry I'm not sure what the output looked like before for #1280 but I'd argue it does look well-formatted now so I guess so 👍

**Pull request merged**
