### PR TITLE
Move JSON check to CodeGen rather than as helper function

### LINKED ISSUE #1495: Code generation can't handle booleans in the parameters dict
Repro:

```python
from evalml.pipelines.utils import generate_pipeline_code
from evalml.pipelines import MulticlassClassificationPipeline
from evalml.pipelines.components import Transformer

class MyTransformer(Transformer):
    name = "I have a bool parameter"

    def __init__(self, do_something=False, random_state=0):
        super().__init__(parameters={'do_something': do_something},
                         component_obj=None,
                         random_state=random_state)

        
class CustomPipeline(MulticlassClassificationPipeline):
    name = "Custom Pipeline"
    component_graph = [MyTransformer,'Random Forest Classifier']

pipeline_instance = CustomPipeline(parameters={})
code = generate_pipeline_code(pipeline_instance)
print(code)


exec(code)
```

```python
from evalml.pipelines.multiclass_classification_pipeline import MulticlassClassificationPipeline

class CustomPipeline(MulticlassClassificationPipeline):
	component_graph = [
		MyTransformer,
		'Random Forest Classifier'
	]
	name = 'Custom Pipeline'

parameters = {
	"I have a bool parameter": {
		"do_something": false
	},
	"Random Forest Classifier": {
		"n_estimators": 100,
		"max_depth": 6,
		"n_jobs": -1
	}
}
pipeline = CustomPipeline(parameters)
```

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-0e2afc7a82c0> in <module>
     21 
     22 
---> 23 exec(code)

<string> in <module>

NameError: name 'false' is not defined
```

### PR DESCRIPTION
**Pull request by bchen1116**
fix #1495 

Follow-up on [this pr](https://github.com/alteryx/evalml/pull/1524#discussion_r538917116). Moved JSON check to CodeGen function, added additional tests

### CODE REVIEW

**Comment by dsherry** [comment]
@bchen1116 did you mean to put this in Review instead of In Progress? I see there are test failures so unsure if its ready for review

**Comment by bchen1116** [comment]
@dsherry it's In Progress for me, but I'll fix these tests and get it up for review soon

**Review by jeremyliweishih — APPROVED** [review]
Is this just to address Dylan's comments? If so, LGTM!

**Review by dsherry — APPROVED** [review]
🚢  looks great!

**Review by angela97lin — APPROVED** [review]
Nice, LGTM! 👍

**Pull request merged**
