### PR TITLE
Release v0.21.0

### PR DESCRIPTION
**Pull request by dsherry**
# v0.21.0 Mar. 24, 2021
### Enhancements
- Changed ``AutoMLSearch`` to default ``optimize_thresholds`` to True #1943
- Added multiple oversampling and undersampling sampling methods as data splitters for imbalanced classification #1775
- Added params to balanced classification data splitters for visibility #1966
- Updated ``make_pipeline`` to not add ``Imputer`` if input data does not have numeric or categorical columns #1967
- Updated ``ClassImbalanceDataCheck`` to better handle multiclass imbalances #1986
- Added recommended actions for the output of data check's ``validate`` method #1968
- Added error message for ``partial_dependence`` when features are mostly the same value #1994
- Updated ``OneHotEncoder`` to drop one redundant feature by default for features with two categories #1997
- Added a ``PolynomialDetrender`` component #1992
### Fixes
- Updated binary classification pipelines to use objective decision function during scoring of custom objectives #1934
### Changes
- Removed ``data_checks`` parameter, ``data_check_results`` and data checks logic from ``AutoMLSearch`` #1935
- Deleted ``random_state`` argument #1985
- Updated Woodwork version requirement to ``v0.0.11`` #1996
### Testing Changes
- Removed ``build_docs`` CI job in favor of RTD GH builder #1974
- Added tests to confirm support for Python 3.9 #1724
- Changed ``build_conda_pkg`` job to use ``latest_release_changes`` branch in the feedstock. #1979
### Breaking Changes
- Changed ``AutoMLSearch`` to default ``optimize_thresholds`` to True #1943
- Removed ``data_checks`` parameter, ``data_check_results`` and data checks logic from ``AutoMLSearch``. To run the data checks which were previously run by default in ``AutoMLSearch``, please call ``DefaultDataChecks().validate(X_train, y_train)`` or take a look at our documentation for more examples. #1935
- Deleted ``random_state`` argument #1985

### CODE REVIEW

**Comment by dsherry** [comment]
Perf test results [here](https://alteryx.quip.com/xYQ9A3Exiga4/v0210-vs-v0200-perf-test-results)

**Review by bchen1116 — APPROVED** [review]
🚀

**Review by angela97lin — APPROVED** [review]

**Review by freddyaboulton — APPROVED** [review]
Looks good @dsherry !

**Pull request merged**
