### PR TITLE
v0.19.0 Release

### PR DESCRIPTION
**Pull request by chukarsten**
# v0.19.0 Feb. 23, 2021
### Enhancements
- Added a GitHub Action for Python windows unit tests #1844
- Added a GitHub Action for checking updated release notes #1849
- Added a GitHub Action for Python lint checks #1837
- Adjusted ``explain_prediction``, ``explain_predictions`` and ``explain_predictions_best_worst`` to handle timeseries problems. #1818
- Updated ``InvalidTargetDataCheck`` to check for mismatched indices in target and features #1816
- Updated ``Woodwork`` structures returned from components to support ``Woodwork`` logical type overrides set by the user #1784
- Updated estimators to keep track of input feature names during ``fit()`` #1794
- Updated ``visualize_decision_tree`` to include feature names in output #1813
- Added ``is_bounded_like_percentage`` property for objectives. If true, the ``calculate_percent_difference`` method will return the absolute difference rather than relative difference #1809
- Added full error traceback to AutoMLSearch logger file #1840
- Changed ``TargetEncoder`` to preserve custom indices in the data #1836
- Refactored ``explain_predictions`` and ``explain_predictions_best_worst`` to only compute features once for all rows that need to be explained #1843
- Added custom random undersampling sampler for classification #1857
- Updated ``OutliersDataCheck`` implementation to calculate the probability of having no outliers #1855
- Added ``Engines`` pipeline processing API #1838
### Changes
- Modified ``calculate_percent_difference`` so that division by 0 is now inf rather than nan #1809
- Removed ``text_columns`` parameter from ``LSA`` and ``TextFeaturizer`` components #1652
- Added ``random_seed`` as an argument to our automl/pipeline/component API. Using ``random_state`` will raise a warning #1798
- Added ``DataCheckError`` message in ``InvalidTargetDataCheck`` if input target is None and removed exception raised #1866
### Testing Changes
- Added back coverage for ``_get_feature_provenance`` in ``TextFeaturizer`` after ``text_columns`` was removed #1842
- Pin graphviz version for windows builds #1847
- Unpin graphviz version for windows builds #1851
.. warning::
### Breaking Changes
- Added a deprecation warning to ``explain_prediction``. It will be deleted in the next release. #1860

### CODE REVIEW

**Review by jeremyliweishih — APPROVED** [review]
LGTM!

**Review by bchen1116 — APPROVED** [review]
Nice!

**Review by dsherry — APPROVED** [review]
ship_revert

**Review by freddyaboulton — APPROVED** [review]

**Comment by angela97lin** [comment]
@dsherry O deer...

**Review by angela97lin — APPROVED** [review]

**Review by ParthivNaresh — APPROVED** [review]

**Review by bchen1116 — APPROVED** [review]

**Pull request merged**
