### PR TITLE
fixed back arrow on install page docs

### PR DESCRIPTION
**Pull request by jpcarroll**
### Pull Request Description
Fixes back arrow on install page of the docs

### CODE REVIEW

**Comment by chukarsten** [comment]
@jpcarroll Thanks for contributing.  I'll check this out now.

**Comment by gsheni** [comment]
Docs Preview:
## Top of Install Page
Screen Shot 2021-02-08 at 2 16 25 PM

## Bottom of Install page
Screen Shot 2021-02-08 at 2 16 21 PM

**Comment by chukarsten** [comment]
@gsheni What causes that to appear at the top of the page?  I can't see RTD yet, but it looks normal on my locally built version...

**Comment by gsheni** [comment]
@chukarsten that is a ReadTheDocs feature. It adds to the top of the HTML to make sure users know the documentation is for a PR. You won't see it when building locally.

**Review by chukarsten — APPROVED** [review]
Looks good! Thanks for contributing!  We'd love to have you check out some of our other good first issues.

**Comment by dsherry** [comment]
@jpcarroll thank you for contributing!

Could you please re-push when you get a chance? We just updated our CI so that it will run properly on PRs from forks. The next time you push, the CI should go all-green.

**Review by dsherry — APPROVED** [review]
Looks good to me! The "back" button on the install page now says "Home" instead of our entire tagline.

@gsheni you may wanna do the same with woodwork

**Comment by tyler3991** [comment]
thanks for contributing @jpcarroll ! We really appreciate it.

**Pull request merged**
