### PR TITLE
Release v0.18.2

### PR DESCRIPTION
**Pull request by ParthivNaresh**
# v0.18.2 Feb. 10, 2021
### Enhancements
- Added uniqueness score data check #1785
- Added "dataframe" output format for prediction explanations #1781
- Updated LightGBM estimators to handle ``pandas.MultiIndex`` #1770
- Sped up permutation importance for some pipelines #1762
- Added sparsity data check #1797
- Confirmed support for threshold tuning for binary time series classification problems #1803
### Documentation Changes
- Added section on conda to the contributing guide #1771
- Updated release process to reflect freezing `main` before perf tests #1787
- Moving some prs to the right section of the release notes #1789
- Tweak README.md. #1800
- Fixed back arrow on install page docs #1795

### CODE REVIEW

**Comment by ParthivNaresh** [comment]
## Main
- [x] CircleCI tests [passed](https://app.circleci.com/pipelines/github/alteryx/evalml?branch=main)
- [x] "Latest" docs build [passed](https://readthedocs.com/projects/feature-labs-inc-evalml/builds/)
- [x] "Latest" documentation looks [good](https://evalml.featurelabs.com/en/latest/)
- [x] Release Notes include the [latest](https://evalml.featurelabs.com/en/latest/release_notes.html) changes on main

## Release branch
- [ ] CirceCI tests [passed](https://app.circleci.com/pipelines/github/alteryx/evalml?branch=release_v0.18.2)
- [ ] "Latest" docs build [passed]()
- [ ] "Latest" documentation looks [good]()
- [ ] Release Notes include the [latest]() changes on main

## Performance Tests
- [ ] Completed

**Review by jeremyliweishih — APPROVED** [review]
:shipit:

**Review by dsherry — APPROVED** [review]
🚢 ! 😁

**Review by angela97lin — APPROVED** [review]
LGTM! 🚢

**Pull request merged**
